services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${rootPassword}"
    ports:
      - "3306:3306"

  mail:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
