services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: linkmanager
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www
  nginx:
    image: nginx
    container_name: linkmanager-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
  db:
    image: mariadb
    container_name: linkmanager-db
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: example
    volumes:
     - ./mariadb:/docker-entrypoint-initdb.d